@startuml

!include NotkaApiRepositoryClasses.puml

IRepositoryBase <|.. RepositoryBase
IRepositoryWrapper <|.. RepositoryWrapper
RepositoryBase <|.. EntityRepository
IEntityRepository <|.. EntityRepository
AGetParameters <|.. EntityParameters
List <|.. PagedList


@enduml